name: Dev Build
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup
        uses: actions/setup-node@1.2.0
        with:
          node-version: '12.x'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Test
        run: npm test

      - name: Build, Tag, and Publish
        uses: mattdavis0351/actions/docker-pgr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: brands-dev

